apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend
  labels:
    {{- include "todo-app.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ include "todo-app.fullname" . }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    {{- include "todo-app.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ include "todo-app.fullname" . }}-frontend
